"""create models

Revision ID: 86ca357a0d3e
Revises: 
Create Date: 2026-08-07 15:57:20.523057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86ca357a0d3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_name', sa.String(), nullable=False),
    sa.Column('topology_type_id', sa.Enum('TORUS', 'MESH', 'TREE', 'FLAT', name='topology_type'), nullable=False),
    sa.Column('dimension', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('wrap', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('client_status_id', sa.Enum('ONLINE', 'OFFLINE', name='client_status'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('node',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('coordinates', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('status_id', sa.Enum('IDLE', 'ALLOCATED', 'MIXED', 'DOWN', name='node_status'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.cluster_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Enum('CPU', 'GPU', 'MEM', name='resource_type'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_period > start_period', name='ck_reservation_valid_period'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Enum('CPU', 'GPU', 'MEM', name='resource_type'), nullable=False),
    sa.Column('consumed_hours', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'CANCELLED', 'FAILED', name='job_status'), nullable=False),
    sa.Column('priority_id', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='priority'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('node_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.node_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_resource',
    sa.Column('resource_node_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Enum('CPU', 'GPU', 'MEM', name='resource_type'), nullable=False),
    sa.Column('resource_type_index', sa.Integer(), nullable=False),
    sa.Column('resource_status_id', sa.Enum('AVAILABLE', 'ALLOCATED', 'UNAVAILABLE', 'FAILED', name='resource_status'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.node_id'], ),
    sa.PrimaryKeyConstraint('resource_node_id')
    )
    op.create_table('allocation',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('allocation_status_id', sa.Enum('PENDING', 'ALLOCATED', 'ACTIVE', 'RELEASED', 'FAILED', name='allocation_status'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('job_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Enum('JOB_SUBMITTED', 'JOB_RUNNING', 'JOB_COMPLETED', 'JOB_CANCELLED', 'JOB_FAILED', 'PLACEMENT_ATTEMPT', name='event_type'), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_requirement',
    sa.Column('req_res_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Enum('CPU', 'GPU', 'MEM', name='resource_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.PrimaryKeyConstraint('req_res_id')
    )
    op.create_table('allocation_node',
    sa.Column('allocation_node_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('resource_node_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocation.allocation_id'], ),
    sa.ForeignKeyConstraint(['resource_node_id'], ['node_resource.resource_node_id'], ),
    sa.PrimaryKeyConstraint('allocation_node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocation_node')
    op.drop_table('resource_requirement')
    op.drop_table('job_event')
    op.drop_table('allocation')
    op.drop_table('node_resource')
    op.drop_table('node_reservation')
    op.drop_table('job')
    op.drop_table('resource_usage')
    op.drop_table('reservation')
    op.drop_table('quota')
    op.drop_table('node')
    op.drop_table('client')
    op.drop_table('groups')
    op.drop_table('cluster')
    # ### end Alembic commands ###
