"""allocation end_time, duration nullable

Revision ID: d070f3f449ac
Revises: 68ab979ef93e
Create Date: 2026-08-17 12:04:01.923425

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd070f3f449ac'
down_revision: str | Sequence[str] | None = '68ab979ef93e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocation', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('allocation', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('allocation', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('allocation', 'end_time')
    # ### end Alembic commands ###
