"""unique constraint on node_resource type_index

Revision ID: ded4d84ae440
Revises: d070f3f449ac
Create Date: 2026-08-17 17:45:47.322429

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ded4d84ae440'
down_revision: str | Sequence[str] | None = 'd070f3f449ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_node_resource_type_index', 'node_resource', ['node_id', 'resource_type', 'resource_type_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_node_resource_type_index', 'node_resource', type_='unique')
    # ### end Alembic commands ###
